# ----
# Site
name: Bad Baby Bakery
title: Bad Baby Bakery by Dana Yakoobinsky
url: "https://www.badbabybakery.com"
baseurl:
google_analytics_key: "UA-100972209-1"
newsletter_action: "//badbabybakery.us16.list-manage.com/subscribe/post?u=c372db4bd5e106da063969984&amp;id=2ef8216c66"
disqus_shortname: bad-baby-bakery

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: images/logo.svg
description: Bad Baby Bakery Blog
author:
  name: Dana Yakoobinsky
  email: dana@badbabybakery.com
  twitter: # twitter username without the @ symbol
social:
  name: Bad Baby Bakery
  links:

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: "/:title/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - Pinterest
